version: '3'
services:
  app:
    build: .                  # Build from Dockerfile in the current directory
    container_name: my-node-container
    ports:
      - "5174:5174"
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
    command: ["npm", "run", "dev"]  # Run npm run dev
