services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile  # Your Dockerfile location
    ports:
      - "5174:5174"  # Map port 5174 of the container to port 5174 on your host
    volumes:
      - .:/usr/src/app  # Mount your application directory
